spring:
#  profiles:
#    active: dev
  application:
    name: microservice-provider-user
  datasource:
    url: jdbc:mysql://localhost:3306/cloud?useSSL=true
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 8080
  servlet-path: /user-api/*
eureka:
  client:
    service-url:
      defaultZone: http://nsk:abcd1234@localhost:8764/eureka/
  instance:
    prefer-ip-address: true
    metadata-map:
      my-metadata: My defined metedata

---
# profiles = peer2时配置信息
spring:
  profiles: peer1
server:
  port: 8082
eureka:
  client:
    service-url:
      defaultZone: http://nsk:abcd1234@localhost:8764/eureka/
---
# profiles = peer2时配置信息
spring:
  profiles: peer2
server:
  port: 8083
eureka:
  client:
    service-url:
      defaultZone: http://nsk:abcd1234@localhost:8764/eureka/

