spring:
  profiles:
    active: dev
  datasource:
    url: jdbc:mysql://localhost:3306/cloud?useSSL=true
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 8080