spring:
  profiles:
    active: dev
  application:
    name: microservice-provider-user
  datasource:
    url: jdbc:mysql://localhost:3306/cloud?useSSL=true
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 8080
  servlet-path: /user-api/*
eureka:
  client:
    service-url:
      defaultZone: http://nsk:abcd1234@localhost:8761/eureka/
  instance:
    prefer-ip-address: true
